dream_ticket/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('stockroom.urls')),

    #url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS

    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^login/$', 'stockroom.views.login', name='login'),
    url(r'^logout/$', 'stockroom.views.logout', name='logout'),
    url(r'^login_redirect/$', 'stockroom.views.login_redirect', name='login_redirect'),

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stockroom/urls.py
from django.conf.urls import patterns, url
from .views import grid, about, product, set_like

urlpatterns = patterns('',
    url(r'^$', grid),
    url(r'^grid/$', grid, name='grid'),
    url(r'^product/(?P<slug>[-\w]+)/$', product, name='product'),
    url(r'^set_like/(?P<id>\d+)/$', set_like, name='set_like'),
    # TODO deprecated url(r'^add_comment/$', add_comment, name='add_comment'),
    url(r'^about/$', about, name='about'),
)

stockroom/models.py
# coding: utf-8
from django.db import models
from django.utils.text import slugify
from datetime import datetime, timedelta
from django.contrib.auth.models import User


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Product name')
    slug = models.SlugField(unique=True, blank=True, verbose_name='Url', help_text='You can fill it manually or leave blank for generate automatic')
    description = models.TextField(blank=True, verbose_name='Product description')
    price = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True, verbose_name='Price')
    created_at = models.DateTimeField(auto_now_add=True, editable=False, blank=True, null=True, verbose_name='Creation date')
    modified_at = models.DateTimeField(blank=True, null=True, auto_now=True, verbose_name='Modified date')

    def get_absolute_url(self):
        return '/product/{}'.format(self.slug)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        if not self.id:
            self.created = datetime.today()

        self.modified = datetime.today()
        return super(Product, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class Like(models.Model):
    user = models.ForeignKey(User)
    product = models.ForeignKey(Product)


class Comment(models.Model):
    user = models.ForeignKey(User)
    product = models.ForeignKey(Product)
    contents = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False, blank=True, null=True, verbose_name='Comment creation date')

    @property
    def within_24h(self):
        if (datetime.now() - self.created_at) < timedelta(days=1):
            return True
        else:
            return False

    def __unicode__(self):
        try:
            create_time = self.created_at.strftime("%d %B %Y, %H:%M")
        except AttributeError:
            create_time = None
        return 'Comment from {} at {}'.format(self.user.username, create_time)

stockroom/forms.py
from django import forms

class CommentForm(forms.Form):
    user_comment = forms.CharField( label='', required=True, widget=forms.TextInput)

stockroom/views.py
# coding: utf-8
from django.db.models import Count
from django.shortcuts import redirect, render_to_response, RequestContext, Http404, HttpResponseRedirect
from django.contrib.auth import login as django_login, authenticate, logout as django_logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from stockroom.models import Product, Like, Comment
from .forms import CommentForm


def about(request):
    return render_to_response('about.html')


def login(request):
    context = RequestContext(request)
    if request.method == 'POST':
        username, password = request.POST['username'], request.POST['password']
        print 'username', username
        print 'pass', password
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                django_login(request, user)
            else:
                #context['error'] = 'Non active user'
                messages.add_message(request, messages.INFO, 'Non active user')
        else:
            messages.add_message(request, messages.ERROR, 'Wrong username or password')

    #return redirect('grid')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def logout(request):
    django_logout(request)
    return redirect('/')


def login_redirect(request):
    messages.add_message(request, messages.ERROR, 'You must be logged in for perform this operation')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def grid(request):
    context_instance = RequestContext(request)

    # for security reasons we limit acceptable 'order_by'
    VALID_SORTS = {
        "name": "name",
        "price": "price",
        "-likes": "-likes",   # we want descent sort
    }
    DEFAULT_SORT = 'name'

    # Choose ordering column and pagination page
    page = request.GET.get('page', 1)
    get_order_by = request.GET.get('order_by', DEFAULT_SORT)
    order_by = VALID_SORTS.get(get_order_by, DEFAULT_SORT)

    # Count likes using 'annotate' feature. Then likes number will be accessible via product_list.likes
    product_list = Product.objects.all().annotate(likes=Count('like')).order_by(order_by)

    # setup pagination for 4 item per page
    paginator = Paginator(product_list, 4)

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products = paginator.page(paginator.num_pages)

    return render_to_response('grid.html', {'products': products, 'order_by': order_by}, context_instance)


def product(request, slug):
    context_instance = RequestContext(request)

    # get appropriate "product" based on slug
    try:
        product = Product.objects.get(slug=slug)
    except product.DoesNotExist:
        raise Http404


    # form handler
    #
    # if user press 'submit', this branch run
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():

            # check if user if logged in
            if request.user.is_authenticated():
                # save comment to database
                user_comment = form.cleaned_data['user_comment']
                comment = Comment()
                comment.user = request.user
                comment.product = product
                comment.contents = user_comment
                comment.save()

                # finally, we clean form
                # form = CommentForm()

                # if a user hits “Refresh” on a page that was loaded via POST, that request will be repeated. http://www.djangobook.com/en/2.0/chapter07.html
                # so we need redirect
                messages.add_message(request, messages.SUCCESS, 'Comment successfully added!')
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            else:
                # if user not logged in, he can't live comments
                return redirect('login_redirect')

    # else we render empty form
    else:
        form = CommentForm()

    # Show users, who like this product
    likes = Like.objects.filter(product=product)

    # We show comment on product page
    comments = Comment.objects.filter(product=product).order_by('created_at').reverse

    return render_to_response('product.html', {'product': product, 'likes': likes, 'form': form, 'comments': comments}, context_instance)


@login_required
def set_like(request, id):
    try:
        product = Product.objects.get(pk=id)
    except:
        raise Http404

    # if user already put like, database contain record with both product and user; so we send red message
    if Like.objects.filter(product=product, user=request.user).exists():
        messages.add_message(request, messages.ERROR, 'You"ve clicked this button already!')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    # create new 'like' record
    like = Like()
    like.user = request.user
    like.product = product
    like.save()

    # return to previous page and conglaturate user
    messages.add_message(request, messages.SUCCESS, 'We are glad for your choice!')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

stockroom/templates/about.html
{% extends "base.html" %}

{% block table %}
{% load staticfiles %}

<div class="container col-md-5 col-md-offset-4">

<div class="well well-lg">
    <h4>Great technology used in this project</h4>
</div>

<table class="table">
    <tr>
        <td><img src="{% static 'logo/python.jpg' %}" height="40px"></td>
        <td><a class="btn btn-default" href="https://www.python.org/" role="button" target="_blank">Python</a></td>
    </tr>
    <tr>
        <td><img src="{% static 'logo/django.png' %}" height="40px"></td>
        <td><a class="btn btn-default" href="https://www.djangoproject.com/" role="button" target="_blank">Django</a></td>
    </tr>
{% comment %}    <tr>
        <td><img src="{% static 'logo/HTML5.png' %}" height="40px"></td>
        <td><a class="btn btn-default" href="https://ru.wikipedia.org/wiki/HTML5" role="button" target="_blank">HTML5</a></td>
    </tr>{% endcomment %}
    <tr>
        <td><img src="{% static 'logo/css.png' %}" height="40px"></td>
        <td><a class="btn btn-default" href="https://ru.wikipedia.org/wiki/CSS" role="button" target="_blank">CSS3</a></td>
    </tr>
    <tr>
        <td><img src="{% static 'logo/Pycharm.png' %}" height="40px"></td>
        <td><a class="btn btn-default" href="https://www.jetbrains.com/pycharm/" role="button" target="_blank">PyCharm</a></td>
    </tr>
    <tr>
        <td><img src="{% static 'logo/ubuntu.png' %}" height="30px"></td>
        <td><a class="btn btn-default" href="http://www.ubuntu.com/" role="button" target="_blank">Ubuntu</a></td>
    </tr>
    <tr>
        <td><img src="{% static 'logo/github.png' %}" height="30px"></td>
        <td><a class="btn btn-default" href="https://github.com/" role="button" target="_blank">Github</a></td>
    </tr>
    <tr>
        <td><img src="{% static 'logo/fabric.png' %}" height="40px"></td>
        <td><a class="btn btn-default" href="http://www.fabfile.org/" role="button" target="_blank">Fabric</a></td>
    </tr>
    <tr>
        <td><img src="{% static 'logo/Nginx.png' %}" height="30px"></td>
        <td><a class="btn btn-default" href="http://nginx.org/ru/" role="button" target="_blank">Nginx</a></td>
    </tr>
    <tr>
        <td><img src="{% static 'logo/postgresql.png' %}" height="40px"></td>
        <td><a class="btn btn-default" href="http://www.postgresql.org/" role="button" target="_blank">Postgresql</a></td>
    </tr>
    <tr>
        <td><img src="{% static 'logo/bootstrap2.png' %}" height="40px"></td>
        <td><a class="btn btn-default" href="http://getbootstrap.com/" role="button" target="_blank">Bootstrap</a></td>
    </tr>
    <tr>
        <td><img src="{% static 'logo/jquery.png' %}" height="40px"></td>
        <td><a class="btn btn-default" href="https://jquery.com/" role="button" target="_blank">Jquery</a></td>
    </tr>
    <tr>
        <td><img src="{% static 'logo/bower.png' %}" height="40px"></td>
        <td><a class="btn btn-default" href="http://bower.io/" role="button" target="_blank">Bower</a></td>
    </tr>
    <tr>
        <td><img src="{% static 'logo/JSON.gif' %}" height="40px"></td>
        <td><a class="btn btn-default" href="http://json.org/" role="button" target="_blank">Json</a></td>
    </tr>

{% comment %}    <tr>
        <td><img src="{% static 'logo/grappelli.png' %}" height="40px"></td>
        <td><a class="btn btn-default" href="http://grappelliproject.com/" role="button" target="_blank">Grappelli</a></td>
    </tr>{% endcomment %}
</table>
</div>

{% endblock %}

stockroom/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        {% get_static_prefix as STATIC_URL %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

        <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap-theme.min.css' %}">

        <link rel="stylesheet" href="{% static "style.css" %}">

        <style type="text/css">
            table {
               font-size: 14px !important;
            }
        </style>

        <title>Stock Room</title>

        {% block head %}  {% endblock %}
    </head>

<body>

<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'grid' %}" class="btn navbar-btn btn-danger" role="button">Stock Room</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav">
                <li><a href="{% url 'about' %}"><span class="glyphicon glyphicon-tag"></span>
                    About</a></li>
            </ul>

            {% if user.is_authenticated %}
                <div class="navbar-form navbar-right btn-group">
                    <a href="{% url 'admin:index' %}" class="btn btn-default" role="button"><span class="glyphicon glyphicon-wrench"></span>Admin</a>
                    <button type="button" class="btn btn-success"><span class="glyphicon glyphicon-user"></span> User '{{ user.username }}' is authenticated.</button>
{#                    <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-log-in"></span> Logout</button>#}
                    <a href="{% url 'logout' %}" class="btn btn-default" role="button"><span class="glyphicon glyphicon-log-in"></span> Logout</a>
                </div>
            {% else %}
                <form name='AuthenticationForm' method="post" action="{% url 'login' %}" class="navbar-form navbar-right" role="form" >
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="sr-only" for="exampleInputUsername2">Login</label>
                        <input type="text" class="form-control" id="exampleInputUsername2" placeholder="Username" name="username">
                    </div>

                    <div class="form-group">
                        <label class="sr-only" for="exampleInputPassword2">Password</label>
                        <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password" name="password">
                    </div>

                    <button type="submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-log-in"></span>
                        <i class="icon-user icon-white"></i> Log in
                    </button>
                </form>
            {% endif %}

        </div>
    </div>
</nav>

{% if messages %}
    <div class="container-fluid">
        <ul class="messages">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert"> {{ message }} </div>
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% block table %}  {% endblock %}

</body>

</html>

stockroom/templates/grid.html
{% extends "base.html" %}

{% block table %}

{% load admin_urls %}
{% load static %}

<div class="container-fluid">
    <table class="table table-striped table-hover table-bordered table-condensed">
            <tr>
                <th><a href="?page={{ products.number }}&order_by=name">Name</a></th>
                <th class="col-md-3">Description</th>
                <th><a href="?page={{ products.number }}&order_by=price">Price</a></th>
                <th>Created</th>
                <th>Modified</th>
                <th>Slug line</th>
                <th><a href="?page={{ products.number }}&order_by=-likes">Like</a></th>
                <th>Edit</th>
            </tr>
        {% for product in products %}
            <tr>
                <td><a href="{% url 'product' product.slug %}">{{ product.name }}</a></td>
                <td><h6>{{ product.description }}</h6></td>
                <td>{{ product.price }}</td>
                <td>{{ product.created_at }}</td>
                <td>{{ product.modified_at }}</td>
                <td>{{ product.slug }}</td>
                <td>{{ product.likes }} <h6>[verify with product.like_set.count: {{product.like_set.count}}]</h6></td>
                <td>
                    <a type="button" class="btn-sm btn-info" href="{% url 'admin:stockroom_product_change' product.pk %}">
                        <span class="glyphicon glyphicon-edit"></span></a>
                </td>
            </tr>
        {% endfor %}

    </table>

    <nav>
        <ul class="pager">
            {% if products.has_previous %}
                <li class="previous"><a href="?page={{ products.previous_page_number }}&order_by={{ order_by }}">previous</a></li>
            {% else %}
                <li class="previous disabled"><a>previous</a></li>
            {% endif %}

            <li>
                <span class="current">
                    {{ products.number }} of {{ products.paginator.num_pages }}
                </span>
            </li>

            {% if products.has_next %}
                <li class="next"><a href="?page={{ products.next_page_number }}&order_by={{ order_by }}">next</a></li>
            {% else %}
                <li class="next disabled"><a>next</a></li>
            {% endif %}
      </ul>
    </nav>



</div>


{% endblock %}

stockroom/templates/product.html
{% extends "base.html" %}

{% block table %}

{% load admin_urls %}

<div class="container-fluid">
    <table class="table table-striped table-hover table-bordered">
        <tr>
            <td class="col-md-1"><b>Product</b></td>
            <td>{{ product.name }}</td>
        </tr>
        <tr>
            <td><b>Description</b></td>
            <td>{{ product.description }}</td>
        </tr>
        <tr>
            <td><b>Price</b></td>
            <td>{{ product.price }}</td>
        </tr>
        <tr>
            <td><b>Liked by</b></td>
            <td>
                {% for like in likes %}
                    <span class="label label-default">{{ like.user }}</span>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <td><b>Like?</b></td>
            <td>
                <a class="btn btn-success" href="{% url 'set_like' product.pk %}" role="button">
                    <span class="glyphicon glyphicon-thumbs-up"></span>
                    I like it!
                </a>
            </td>
        </tr>
    </table>

    <h6> Comments within last 24h are green </h6>

    <div class="panel panel-primary">
        <div class="panel-heading">User's comments:</div>
        <table class="table table-striped table-hover table-bordered">
            {% for comment in comments %}
                <tr {% if comment.within_24h %} class="success" {% else %} class="active" {% endif %}>
                    <td class="col-md-1"> <b>{{ comment.user }}</b> </td>
                    <td> {{ comment.contents }} </td>
                    <td class="col-md-2"> {{ comment.created_at }} </td>
                </tr>
            {% endfor %}
        </table>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">Your comment:</div>
        <form action="." method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit" />
        </form>
    </div>

</div>

{% endblock %}